language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t my_app -f dockerfile.dev .

script:
  - docker run -e CI=true my_app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker react test"
  env: "Dockerreacttest-env"
  bucket_name: "elasticbeanstalk-us-east-2-916446640976"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
